[tool.poetry]
name = "project2"
version = "0.1.0"
description = ""
authors = ["Kuprin Aleksandr <freeman8901@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
